### ISSUE TITLE
[Other] SSL Support

### ISSUE THREAD

**Issue by CodeAlDente** [flightphp/flightphp.com#10]
Is there a reason why flightphp.com does not support a secure connection via https? From what I know this is possible with custom domains as described here: https://github.blog/2018-05-01-github-pages-custom-domains-https/

**Comment by BaseMax** [comment]
This request is a bit old and it is a good thing that it has been done well.
The website is now secure and uses a Let's Encrypt **SSL** certificate.

Thank you
