### ISSUE TITLE
Range & Head

### ISSUE THREAD

**Issue by swschilke** [flightphp/flightphp.com#11]
How does a flightphp REST "endpoint" reacts if a Head or Range http request is used against the endpoint? Or a trace / connect etc.?

**Comment by mikecao** [comment]
As long as the request method gets passed to Flight, it can handle it.

**Comment by swschilke** [comment]
Well, range requests from a resource, e.g. the bytes 200-2000. Can it handle this? Like www.your.domain/files/some.file (<-- the rest call) with range 200-2000 in the request. How does flightphp react/handle this?

**Comment by mikecao** [comment]
It will just pass the request to your handler. Your handler will need to respond appropriately. There is no built in file handling in Flight.
