### ISSUE TITLE
requests beyond level 1 aren't working

### ISSUE THREAD

**Issue by jpodpro** [flightphp/flightphp.com#7]
this works:
```
Flight::route('/api', function()
{
	echo "api";
});
```

this doesnt (404 not found):
```
Flight::route('/api/settings', function($name)
{
	echo "settings";
});
```

**Comment by jpodpro** [comment]
discovered that, despite people saying that rewrite can be specified inside the VirtualHost, it cannot. MUST be defined in a .htaccess file.

**Comment by fpaxton** [comment]
FWIW, my particular circumstance took some additional configuration with `<LocationMatch>` to setup the rewrite. But I got it working in the VirtualHost and did not need to use a .htaccess file.
