### ISSUE TITLE
Method to run before any route executes

### ISSUE THREAD

**Issue by jsantari** [flightphp/flightphp.com#9]
Love Flight - is there any way to attach a method to run before any route executes? I have an Authentication method that currently I have to put at the beginning of each routes function. Would be nice to call it automatically without adding that code to each route function.

**Comment by levinside** [comment]
Yes.
`Flight::before($name, $callback) // Adds a filter before a framework method.`
Please read [Filtering](http://flightphp.com/learn/#filtering) section in Docs. 

Yours case will look like this:
```
Flight::before('start', function(&$params, &$output){
  // make auth here
});
```

**Comment by Prid13** [comment]
#### BEFORE every route: `Flight::before('start', $callbackFn)`
#### AFTER every route: `Flight::before('stop', $callbackFn)`

------

Just adding to what levinside said to clarify this as I was quite confused myself.

- `Flight::before` / `Flight::after` executes before or after any _Flight methods_ OR any custom methods.
- `Flight::start` is a built-in method that starts the whole Flight framework and parses the endpoint and reutrns the appropriate response as per your route methods _each time you navigate to an endpoint_. In other words, it runs at the _start_ of _every_ route endpoint (= every time someone goes to that URL endpoint the code runs, and `start` is executed)
- Therefore, `Flight::before('start', $callbackFn)` runs _before_ every `Flight::start()` call, and so _before_ every route code

Alternatively, using `Flight::before('route', $callbackFn)` also works :)

HOWEVER, if you'd also like for code to run _after_ every route code, you CANNOT use `Flight::after('route', $callbackFn)` or `Flight::after('start', $callbackFn)`.

Use `Flight::before('stop', $callbackFn)` if you want code to run _after_ every route endpoint, as `Flight::stop` is called _after_ the route endpoint has been processed and the response has been sent.

-------

For my use case, I wanted to open a new MySQLi connection _before_ every route, and close it _after_ every route. Here's the code I managed to scrape together after viewing the examples:

```php
Flight::register('db', 'mysqli', array('localhost', 'db_user', 'db_pass', 'db_name'));

// use Flight::db() in route codes to get instance of mysqli, e.g.: $mysqli = Flight::db();

Flight::before('start', function(&$params, &$output){
  $con = Flight::db(false); // new mysqli connection
  if($con->connect_error) {
    exit('Error connecting to database');
  }
});

Flight::before('stop', function(&$params, &$output){
  Flight::db()->close(); // close mysqli connection
});
```
